/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppIncomeRouteImport } from './routes/_app.income'
import { Route as AppHardwareRouteImport } from './routes/_app.hardware'
import { Route as AppHackRouteImport } from './routes/_app.hack'
import { Route as AppAccountRouteImport } from './routes/_app.account'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppHardwareRoute = AppHardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => AppRoute,
} as any)
const AppHackRoute = AppHackRouteImport.update({
  id: '/hack',
  path: '/hack',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRoute
  '/hack': typeof AppHackRoute
  '/hardware': typeof AppHardwareRoute
  '/income': typeof AppIncomeRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRoute
  '/hack': typeof AppHackRoute
  '/hardware': typeof AppHardwareRoute
  '/income': typeof AppIncomeRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/hack': typeof AppHackRoute
  '/_app/hardware': typeof AppHardwareRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/login': typeof AuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/hack'
    | '/hardware'
    | '/income'
    | '/settings'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/hack'
    | '/hardware'
    | '/income'
    | '/settings'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/account'
    | '/_app/hack'
    | '/_app/hardware'
    | '/_app/income'
    | '/_app/settings'
    | '/_auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hardware': {
      id: '/_app/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof AppHardwareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hack': {
      id: '/_app/hack'
      path: '/hack'
      fullPath: '/hack'
      preLoaderRoute: typeof AppHackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppHackRoute: typeof AppHackRoute
  AppHardwareRoute: typeof AppHardwareRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppHackRoute: AppHackRoute,
  AppHardwareRoute: AppHardwareRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
